import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Share_Tech_Mono } from "next/font/google";
import { AiFillGithub, AiOutlineTeam } from "react-icons/ai";

const share = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Essai-Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          className={`${share.className} sticky top-0 left-0 right-0 w-[100vw] bg-gradient-to-b from-[#000000c9] via-[#0000009f] to-[#00000000] h-32 text-white flex items-center`}
        >
          <div className="lg:mx-[35vh] mx-[13vh] flex justify-between items-center w-full">
            <Link
              href={""}
              className=" hover:opacity-50 transition duration-150"
            >
              <h1 className="text-2xl">Novel Ai</h1>
            </Link>
            <div className="flex gap-10">
              <Link
                href={"#Team"}
                className=" hover:opacity-50 transition duration-150"
              >
                <h1 className="flex gap-2 text-xl">
                  Our-Team
                  <span className="mt-1">
                    <AiOutlineTeam />
                  </span>
                </h1>
              </Link>
              <Link
                href={"https://github.com/hrithikvinayakr/nah"}
                className=" hover:opacity-50 transition duration-150"
              >
                <h1 className="flex gap-2 text-xl">
                  Github{" "}
                  <span className="mt-1">
                    <AiFillGithub />
                  </span>
                </h1>
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
